FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libffi-dev \
    libssl-dev \
    awscli \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire src directory
COPY src /app/src

# Set the Python path
ENV PYTHONPATH=/app

# Use the new entry point script
CMD ["python", "-m", "src.run_collector"]